name: Python Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-python-app .

    - name: Run Unit Tests inside Docker
      run: docker run my-python-app pytest
